# Generated by Django 4.1.7 on 2023-03-08 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('section', models.CharField(choices=[('Programming', 'Programming'), ('Anime', 'Anime'), ('Gaming', 'Gaming')], max_length=12)),
                ('topic', models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('React', 'React'), ('Django', 'Django')], max_length=11)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('minutes_to_read', models.IntegerField(default=5)),
                ('image', models.ImageField(default='bloglist-1.jpg', upload_to='post_images')),
            ],
        ),
    ]
