# Generated by Django 4.1.7 on 2023-03-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='topic',
            field=models.CharField(choices=[('Javascript', 'Javascript'), ('Python', 'Python'), ('React', 'React'), ('Django', 'Django')], max_length=11, null=True),
        ),
    ]
