# Generated by Django 4.1.7 on 2023-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Anime', 'Anime'), ('Gaming', 'Gaming')], default='Programming', max_length=12),
        ),
    ]
